/**
 * Created by nitiraj on 18/4/14.
 */
define(["core/Constants"], function (Constants) {

    var DEFAULT_OPTIONS = {};


    DEFAULT_OPTIONS[Constants.STAGE_CONTAINERDIV] = "containerDiv";
    DEFAULT_OPTIONS[Constants.STAGE_HEIGHT] = 500;
    DEFAULT_OPTIONS[Constants.STAGE_WIDTH] = 500;
    DEFAULT_OPTIONS[Constants.STAGE_COLOR_RED] = 256;
    DEFAULT_OPTIONS[Constants.STAGE_COLOR_BLUE] = 0;
    DEFAULT_OPTIONS[Constants.STAGE_COLOR_GREEN] = 0;
    DEFAULT_OPTIONS[Constants.STAGE_OPACITY] = 1;

    DEFAULT_OPTIONS[Constants.VAR_BOX_LENGTH] = 50;

    DEFAULT_OPTIONS[Constants.STACK_BOX_WIDTH] = 50;
    DEFAULT_OPTIONS[Constants.STACK_BOX_HEIGHT] = 30;
    DEFAULT_OPTIONS[Constants.STACK_BOX_BORDER_COLOR] = "00000";
    DEFAULT_OPTIONS[Constants.STACK_BOX_INIT_COLOR] = "FFFF33";
    DEFAULT_OPTIONS[Constants.STACK_BOX_FINAL_COLOR] = "0066CC";
    DEFAULT_OPTIONS[Constants.STACK_BOX_TEXT_COLOR] = "00000";

    DEFAULT_OPTIONS[Constants.CODE_FONT_SIZE] = 20;
    DEFAULT_OPTIONS[Constants.CODE_COLOR] = 'black';
    DEFAULT_OPTIONS[Constants.CODE_HIGHLIGHT_COLOR] = 'red';
    DEFAULT_OPTIONS[Constants.CODE_HIGHLIGHT_FONT_SIZE] = 24;

    DEFAULT_OPTIONS[Constants.ARROW_FROMX ] = 0;
    DEFAULT_OPTIONS[Constants.ARROW_FROMY ] = 0;
    DEFAULT_OPTIONS[Constants.ARROW_TOX ] = 1;
    DEFAULT_OPTIONS[Constants.ARROW_TOY ] = 1;
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_LENGTH ] = 10;
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_WIDTH ] = 1;
    DEFAULT_OPTIONS[Constants.ARROW_TAIL_COLOR ] = "red";
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_COLOR ] = "blue";
    DEFAULT_OPTIONS[Constants.ARROW_TAIL_WIDTH ] = 1;
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_SOLID ] = true;
    DEFAULT_OPTIONS[Constants.ARROW_TAIL_TEXT ] = "";
    DEFAULT_OPTIONS[Constants.ARROW_TAIL_TEXT_FONT_SIZE ] = 10;
    DEFAULT_OPTIONS[Constants.ARROW_TAIL_TEXT_COLOR ] = "black";
    DEFAULT_OPTIONS[Constants.ARROW_TAIL_TEXT_FONT ] = "Calibri";
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_TEXT ] = "";
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_TEXT_FONT_SIZE ] = 10;
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_TEXT_COLOR ] = "black";
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_TEXT_FONT ] = "Calibri";
    DEFAULT_OPTIONS[Constants.ARROW_HEAD_HEIGHT] = 2;

    DEFAULT_OPTIONS[Constants.LINKEDLIST_BOX_WIDTH ] = 50;
    DEFAULT_OPTIONS[Constants.LINKEDLIST_BOX_HEIGHT ] = 30;
    DEFAULT_OPTIONS[Constants.LINKEDLIST_POINTER_LENGTH ] = 30;
    DEFAULT_OPTIONS[Constants.TEXT_FONT_FAMILY ] = "Calibri";
    DEFAULT_OPTIONS[Constants.TEXT_FILL_COLOR ] = "black";
    DEFAULT_OPTIONS[Constants.TEXT_FONT_SIZE] = 20;
    DEFAULT_OPTIONS[Constants.TEXT_ALIGN ] = "center";
    DEFAULT_OPTIONS[Constants.TEXT_WIDTH ] = 50;
    DEFAULT_OPTIONS[Constants.RECT_WIDTH ] = 50;
    DEFAULT_OPTIONS[Constants.RECT_HEIGHT ] = 30;
    DEFAULT_OPTIONS[Constants.RECT_FILL_COLOR ] = "#E0FFFF";
    DEFAULT_OPTIONS[Constants.RECT_STROKE_COLOR ] = "black";
    DEFAULT_OPTIONS[Constants.RECT_STROKE_WIDTH ] = 2;
    DEFAULT_OPTIONS[Constants.RECT_HIGHLIGHT_COLOR] = "yellow";

    DEFAULT_OPTIONS[Constants.ARRAY_BOX_WIDTH] = 30;
    DEFAULT_OPTIONS[Constants.ARRAY_BOX_HEIGHT] = 30;


    DEFAULT_OPTIONS[Constants.BINARY_TREE_BOX_WIDTH] = 50;
    DEFAULT_OPTIONS[Constants.BINARY_TREE_BOX_HEIGHT] = 30;

    DEFAULT_OPTIONS[Constants.ANIMATION_UNIT_TIME] = 100; // miliseconds

    DEFAULT_OPTIONS[Constants.ANIMATION_CONTROL_BUTTON_WIDTH] = 50;
    DEFAULT_OPTIONS[Constants.ANIMATION_CONTROL_BUTTON_HEIGHT] = 50;

    DEFAULT_OPTIONS[Constants.ANIMATION_TYPE] = Constants.ANIMATION_TYPE_CODE_ANIMATION;

    DEFAULT_OPTIONS[Constants.ANIMATION_CONTROL_Y] = 0;
    DEFAULT_OPTIONS[Constants.ANIMATION_CONTROL_X] = 0;

    return DEFAULT_OPTIONS;
});