var Logger = new LoggerClass();

jsav.DEFAULT_OPTIONS[jsav.STAGE_CONTAINERDIV] = "containerDiv";
jsav.DEFAULT_OPTIONS[jsav.STAGE_HEIGHT] = 500;
jsav.DEFAULT_OPTIONS[jsav.STAGE_WIDTH] = 500;
jsav.DEFAULT_OPTIONS[jsav.VAR_BOX_LENGTH] = 50;
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_WIDTH] = 50;
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_HEIGHT] = 30;
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_BORDER_COLOR] = "00000";
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_INIT_COLOR] = "FFFF33";
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_FINAL_COLOR] = "0066CC";
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_TEXT_COLOR] = "00000";
jsav.DEFAULT_OPTIONS[jsav.CODE_FONT_SIZE] = 20;
jsav.DEFAULT_OPTIONS[jsav.CODE_COLOR] = 'black';
jsav.DEFAULT_OPTIONS[jsav.CODE_HIGHLIGHT_COLOR] = 'red';
jsav.DEFAULT_OPTIONS[jsav.CODE_HIGHLIGHT_FONT_SIZE] = 24;
