/**
 * Created by nitiraj on 18/4/14.
 */
jsav.DEFAULT_OPTIONS = {};


jsav.DEFAULT_OPTIONS[jsav.STAGE_CONTAINERDIV] = "containerDiv";
jsav.DEFAULT_OPTIONS[jsav.STAGE_HEIGHT] = 500;
jsav.DEFAULT_OPTIONS[jsav.STAGE_WIDTH] = 500;
jsav.DEFAULT_OPTIONS[jsav.STAGE_COLOR_RED] = 256;
jsav.DEFAULT_OPTIONS[jsav.STAGE_COLOR_BLUE] = 0;
jsav.DEFAULT_OPTIONS[jsav.STAGE_COLOR_GREEN] = 0;
jsav.DEFAULT_OPTIONS[jsav.STAGE_OPACITY] = 1;

jsav.DEFAULT_OPTIONS[jsav.VAR_BOX_LENGTH] = 50;
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_WIDTH] = 50;
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_HEIGHT] = 30;
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_BORDER_COLOR] = "00000";
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_INIT_COLOR] = "FFFF33";
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_FINAL_COLOR] = "0066CC";
jsav.DEFAULT_OPTIONS[jsav.STACK_BOX_TEXT_COLOR] = "00000";
jsav.DEFAULT_OPTIONS[jsav.CODE_FONT_SIZE] = 20;
jsav.DEFAULT_OPTIONS[jsav.CODE_COLOR] = 'black';
jsav.DEFAULT_OPTIONS[jsav.CODE_HIGHLIGHT_COLOR] = 'red';
jsav.DEFAULT_OPTIONS[jsav.CODE_HIGHLIGHT_FONT_SIZE] = 24;

jsav.DEFAULT_OPTIONS[jsav.ARROW_FROMX ]= 0;
jsav.DEFAULT_OPTIONS[jsav.ARROW_FROMY ]= 0;
jsav.DEFAULT_OPTIONS[jsav.ARROW_TOX ]= 1;
jsav.DEFAULT_OPTIONS[jsav.ARROW_TOY ]= 1;
jsav.DEFAULT_OPTIONS[jsav.ARROW_HEAD_LENGTH ]= 10;
jsav.DEFAULT_OPTIONS[jsav.ARROW_HEAD_WIDTH ]= 1;
jsav.DEFAULT_OPTIONS[jsav.ARROW_TAIL_COLOR ]= "red";
jsav.DEFAULT_OPTIONS[jsav.ARROW_HEAD_COLOR ]= "blue";
jsav.DEFAULT_OPTIONS[jsav.ARROW_TAIL_WIDTH ]= 1;
jsav.DEFAULT_OPTIONS[jsav.ARROW_HEAD_SOLID ]= true;
jsav.DEFAULT_OPTIONS[jsav.ARROW_TAIL_TEXT ]= "P";
jsav.DEFAULT_OPTIONS[jsav.ARROW_TAIL_TEXT_FONT_SIZE ]= 10;
jsav.DEFAULT_OPTIONS[jsav.ARROW_TAIL_TEXT_COLOR ]= "black";
jsav.DEFAULT_OPTIONS[jsav.ARROW_TAIL_TEXT_FONT ]= "Calibri";
jsav.DEFAULT_OPTIONS[jsav.ARROW_HEAD_HEIGHT] = 2;