jsav = {
	VAR_BOX_LENGTH : 50,
	
	STACK_BOX_WIDTH : 50,
	STACK_BOX_HEIGHT : 30,

	STACK_BOX_BORDER_COLOR : "00000",
	STACK_BOX_INIT_COLOR : "FFFF33",
	STACK_BOX_FINAL_COLOR : "0066CC",
	STACK_BOX_TEXT_COLOR : "00000",
	CODE_FONT_SIZE : 20,
	CODE_COLOR : 'black',
	CODE_HIGHLIGHT_COLOR : 'red',
	CODE_HIGHLIGHT_FONT_SIZE : 24,
};
